# -*- coding: utf-8 -*-
"""Final

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mE5FnyUrUhJIQx-DieJJqfy_sazRreay
"""

from google.colab import files
import pandas as pd
import numpy as np
from sklearn import datasets, linear_model
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from scipy.stats import kstest, norm
from pandas import ExcelWriter
import xlrd 
from sklearn.preprocessing import Imputer
import math

uploaded = files.upload()

df = []
for fn in uploaded.keys():
  df.append(pd.read_excel(fn, na_values='?'))

sg = []
for key, item in df[0]['sg'].items():
  if item > 1.02:
    sg.append(item / 1000)
  else:
    sg.append(item + 0.005)
df[0]['sg'] = sg

# mean
mean_value=df[0]['age'].mean()
df[0]['age'] = df[0]['age'].fillna(math.ceil(mean_value))
mean_value=df[0]['bp'].mean()
df[0]['bp'] = df[0]['bp'].fillna(math.ceil(mean_value))
mean_value=df[0]['sg'].mean()
df[0]['sg'] = df[0]['sg'].fillna(math.ceil(mean_value))
mean_value = df[0]['al'].mean()
df[0]['al'] = df[0]['al'].fillna(math.ceil(mean_value))
mean_value = df[0]['su'].mean()
df[0]['su'] = df[0]['su'].fillna(math.ceil(mean_value))
mean_value = df[0]['sc'].mean()
df[0]['sc'] = df[0]['sc'].fillna(mean_value)
mean_value = df[0]['sod'].mean()
df[0]['sod'] = df[0]['sod'].fillna(math.ceil(mean_value))
mean_value = df[0]['pot'].mean()
df[0]['pot'] = df[0]['pot'].fillna(mean_value)
mean_value = df[0]['hemo'].mean()
df[0]['hemo'] = df[0]['hemo'].fillna(mean_value)
mean_value = df[0]['pcv'].mean()
df[0]['pcv'] = df[0]['pcv'].fillna(math.ceil(mean_value))
mean_value = df[0]['wc'].mean()
df[0]['wc'] = df[0]['wc'].fillna(math.ceil(mean_value))
mean_value = df[0]['rc'].mean()
df[0]['rc'] = df[0]['rc'].fillna(mean_value)
# median
median = df[0]['bgr'].median()
df[0]['bgr'] = df[0]['bgr'].fillna(median)
median = df[0]['bu'].median()
df[0]['bu'] = df[0]['bu'].fillna(median)

# mode
df[0]['rbc'] = df[0]['rbc'].fillna(df[0]['rbc'].mode()[0])
df[0]['pc'] = df[0]['pc'].fillna(df[0]['pc'].mode()[0])
df[0]['pcc'] = df[0]['pcc'].fillna(df[0]['pcc'].mode()[0])
df[0]['ba'] = df[0]['ba'].fillna(df[0]['ba'].mode()[0])
df[0]['htn'] = df[0]['htn'].fillna(df[0]['htn'].mode()[0])
df[0]['htn'] = df[0]['htn'].fillna(df[0]['htn'].mode()[0])
df[0]['cad'] = df[0]['cad'].fillna(df[0]['cad'].mode()[0])
df[0]['appet'] = df[0]['appet'].fillna(df[0]['appet'].mode()[0])
df[0]['pe'] = df[0]['pe'].fillna(df[0]['pe'].mode()[0])
df[0]['ane'] = df[0]['ane'].fillna(df[0]['ane'].mode()[0])
df[0]['class'] = df[0]['class'].fillna(df[0]['class'].mode()[0])

writer = ExcelWriter('Result.xlsx')
df[0].to_excel(writer,'Hoja1')

writer.save()
files.download("Result.xlsx")