# -*- coding: utf-8 -*-
"""Kmeans

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RFUmdZNJbAGTVeHeswzFfHHTpINaYDax
"""

from google.colab import files
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.cluster import KMeans
from sklearn.metrics import pairwise_distances_argmin_min
from mpl_toolkits.mplot3d import Axes3D
plt.rcParams['figure.figsize'] = (16, 9)
plt.style.use('ggplot')

uploaded = files.upload()

df = []
for fn in uploaded.keys():
  df.append(pd.read_excel(fn))

X = np.array(df[0][["age","hemo","htn","dm","class"]])
y = np.array(df[0]['age'])
X.shape

Nc = range(1, 20)
kmeans = [KMeans(n_clusters=i) for i in Nc]
kmeans
score = [kmeans[i].fit(X).score(X) for i in range(len(kmeans))]
score
plt.plot(Nc,score)
plt.xlabel('Numero de clusters')
plt.ylabel('Score')
plt.title('Curva')
plt.show()

kmeans = KMeans(n_clusters=2).fit(X)
centroids = kmeans.cluster_centers_

labels = kmeans.predict(X)
C = kmeans.cluster_centers_
colors=['red','green']
assign=[]
for row in labels:
    assign.append(colors[row])
fig = plt.figure()
ax = Axes3D(fig)
ax.scatter(X[:, 0], X[:, 1], X[:, 2],X[:, 3], c=assign)
ax.scatter(C[:, 0], C[:, 1], C[:, 2],C[:, 3], marker='*', c=colors)

# Predicting the clusters
labels = kmeans.predict(X)
# Getting the cluster centers
C = kmeans.cluster_centers_
colors=['red','green']
assign=[]
for row in labels:
    assign.append(colors[row])
plt.scatter(X[:, 0], X[:, 1],c=assign)
plt.scatter(C[:, 0], C[:, 1], marker='*', c=colors)
plt.show()

closest, _ = pairwise_distances_argmin_min(kmeans.cluster_centers_, X)
closest

tipo=df[0]['class'].values
for row in closest:
    print(tipo[row])

X_new = df[1][["age","hemo","htn","dm", "class"]]
 
new_labels = kmeans.predict(X_new)
for key,pacient in df[1]["age"].items():
  if new_labels[key] == 2:
    print("Paciente",key, "No tiene riesgo de insuficiencia renal", new_labels[key])
  else:
    print("Paciente",key, "Presenta riesgos de insuficiencia renal", new_labels[key])